version: "2.0"
services: 

    minio:
        image: minio/minio:RELEASE.2021-01-16T02-19-44Z
        volumes:
        - ./miniodata:/data
        expose:
        - "9000"
        environment:
            MINIO_ROOT_USER: $MINIO_ACCESS_KEY
            MINIO_ROOT_PASSWORD: $MINIO_SECRET_KEY
        command: server /data
        ports:
            - 9000:9000

    redis:
        image: redis:6.0.9
        volumes:
            - ./redisdata:/data
        ports:
            - 6379:6379
        command: 
            redis-server --requirepass ${REDIS_PASSWORD}

    candc:
        image: ravenscroftj/candc_coresc:latest
        ports:
            - 9004:9004

    worker:
        image: ravenscroftj/sapienta:latest
        environment: 
            - SAPIENTA_CANDC_SOAP_LOCATION=http://candc:9004/
            - REDIS_HOST=redis
            - MINIO_HOST=minio:9000
            - MINIO_USE_SSL=0
            - REDIS_PASSWORD
            - MINIO_BUCKET
            - MINIO_ACCESS_KEY
            - MINIO_SECRET_KEY

        command: dramatiq --threads 1 sapienta.worker
        
    web:
        image: ravenscroftj/sapienta:latest
        environment:
            - REDIS_HOST=redis
            - MINIO_HOST=minio:9000
            - MINIO_USE_SSL=0
            - REDIS_PASSWORD
            - MINIO_BUCKET
            - MINIO_ACCESS_KEY
            - MINIO_SECRET_KEY

        ports:
            - 8000:8000
        command:
            uvicorn --host=0.0.0.0 sapienta.api:app
